const DELIVERY = "Delivery"
const POMODORO_LENGTH = 25
const SHORT_BREAK_LENGTH = 5
const LONG_BREAK_LENGTH = 15
const LONG_BREAK_INTERVAL = 4

export default {
  POMODORO_LENGTH: POMODORO_LENGTH,
  SHORT_BREAK_LENGTH: SHORT_BREAK_LENGTH,
  LONG_BREAK_LENGTH: LONG_BREAK_LENGTH,
  LONG_BREAK_INTERVAL: LONG_BREAK_INTERVAL
}
